### ISSUE TITLE
Unable to download the Installer (HTTP ERROR 502)

### ISSUE THREAD

**Issue by b4imetu** [darktohka/clean-flash-builds#13]
https://bluepload.unstable.life/cleanflash3400282installer1.exe
How to solve HTTP ERROR 502
Is it possible to host the [Installer](https://bluepload.unstable.life/cleanflash3400282installer1.exe) to another URL and distribute it in another way?

**Comment by darktohka** [comment]
Bluepload is now back up. Thanks for letting me know!
