### ISSUE TITLE
Revision 201 32-bit manifest

### ISSUE THREAD

**Issue by sombraguerrero** [darktohka/clean-flash-builds#7]
There's a mistake in the Flash32 manifest for Pepper where the architecture is x64 instead of ia32.

**Comment by darktohka** [comment]
Thanks for the report! Does this issue actually have any effect on the usage of the plugin or is it simply cosmetic?

**Comment by sombraguerrero** [comment]
It affects usage. In my case, I'm using an old version of Chromium and when the manifest it out of alignment, it refuses to recognize the updated binary, even after updating the registry entries.

**Comment by darktohka** [comment]
Hello!

Revision 209 was released today, with the correct 32-bit manifests. Please let me know if the issue has been fixed.

**Comment by sombraguerrero** [comment]
Yes, this has absolutely resolved the issue. Thank you!
